// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCi7ZhhFalBPlxwn3uWBccUAelbuBcsYI',
    appId: '1:1046736351040:web:8554be45efbe71ffde14a5',
    messagingSenderId: '1046736351040',
    projectId: 'smartdairyerp',
    authDomain: 'smartdairyerp.firebaseapp.com',
    storageBucket: 'smartdairyerp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9iSPR1npfWII_OmVCAtUfZYRy_uarmI',
    appId: '1:1046736351040:android:7b411b4693cc2001de14a5',
    messagingSenderId: '1046736351040',
    projectId: 'smartdairyerp',
    storageBucket: 'smartdairyerp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2bp-Djy00uSRQ83H2Dj9JE-hzzNLOuc',
    appId: '1:1046736351040:ios:8381060dbf943b36de14a5',
    messagingSenderId: '1046736351040',
    projectId: 'smartdairyerp',
    storageBucket: 'smartdairyerp.firebasestorage.app',
    iosBundleId: 'com.example.smartDairyErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2bp-Djy00uSRQ83H2Dj9JE-hzzNLOuc',
    appId: '1:1046736351040:ios:8381060dbf943b36de14a5',
    messagingSenderId: '1046736351040',
    projectId: 'smartdairyerp',
    storageBucket: 'smartdairyerp.firebasestorage.app',
    iosBundleId: 'com.example.smartDairyErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCi7ZhhFalBPlxwn3uWBccUAelbuBcsYI',
    appId: '1:1046736351040:web:80ba871cea96abe0de14a5',
    messagingSenderId: '1046736351040',
    projectId: 'smartdairyerp',
    authDomain: 'smartdairyerp.firebaseapp.com',
    storageBucket: 'smartdairyerp.firebasestorage.app',
  );
}
